import { Link } from 'react-router-dom'

const About = () => {
  const features = [
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      ),
      title: 'Smart Player Search',
      description: 'Search across thousands of players from major leagues worldwide with real-time data from RapidAPI. Find players by name, position, club, or nationality.',
      color: 'from-emerald-500 to-emerald-600'
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
        </svg>
      ),
      title: 'Player Analysis',
      description: 'Get detailed player statistics including goals, assists, appearances, and performance metrics. Track player development over time.',
      color: 'from-blue-500 to-blue-600'
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
        </svg>
      ),
      title: 'Compare Players',
      description: 'Compare multiple players side-by-side with detailed statistical breakdowns. Make informed decisions about player quality and value.',
      color: 'from-purple-500 to-purple-600'
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      ),
      title: 'Squad Builder',
      description: 'Build your dream XI with our interactive squad builder. Choose formations, add players, and visualize your complete team.',
      color: 'from-amber-500 to-amber-600'
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
        </svg>
      ),
      title: 'AI Insights',
      description: 'Get AI-powered scouting reports generated by Groq\'s advanced language models. Understand player strengths, weaknesses, and potential.',
      color: 'from-cyan-500 to-cyan-600'
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      ),
      title: 'Fast & Reliable',
      description: 'Powered by modern technology with intelligent caching. Get instant access to player data without rate limits or delays.',
      color: 'from-pink-500 to-pink-600'
    }
  ]

  const stats = [
    { value: '50K+', label: 'Players' },
    { value: '30+', label: 'Leagues' },
    { value: '20+', label: 'Countries' },
    { value: 'Real-time', label: 'Data Updates' }
  ]

  return (
    <div className="min-h-screen bg-[#0a0e17]">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-[#10b981]/10 rounded-full blur-[120px]" />
          <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-blue-500/5 rounded-full blur-[100px]" />
        </div>

        <div className="relative max-w-5xl mx-auto px-4 pt-16 pb-20 text-center">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white mb-6">
            About{' '}
            <span className="bg-gradient-to-r from-[#10b981] to-[#34d399] bg-clip-text text-transparent">
              FutScout
            </span>
          </h1>
          <p className="text-xl text-[#94a3b8] max-w-3xl mx-auto mb-8">
            The future of football scouting. Discover, analyze, and compare players from leagues around the world with AI-powered insights.
          </p>

          <div className="flex flex-wrap justify-center gap-4">
            <Link
              to="/search"
              className="px-8 py-4 bg-gradient-to-r from-[#10b981] to-[#059669] text-white font-semibold rounded-xl hover:from-[#059669] hover:to-[#047857] transition-all shadow-lg shadow-emerald-500/20"
            >
              Start Scouting
            </Link>
            <Link
              to="/squad-builder"
              className="px-8 py-4 bg-[#1e293b] text-white font-semibold rounded-xl hover:bg-[#334155] transition-all border border-[#334155]"
            >
              Build Your Squad
            </Link>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-12 bg-[#0f172a]/50 border-y border-[#1e293b]">
        <div className="max-w-5xl mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <p className="text-4xl font-bold text-[#10b981] mb-2">{stat.value}</p>
                <p className="text-[#64748b]">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4">Powerful Features</h2>
            <p className="text-[#94a3b8] max-w-2xl mx-auto">
              Everything you need for comprehensive football player analysis and scouting
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <div
                key={index}
                className="group bg-[#0f172a] rounded-xl border border-[#1e293b] p-6 hover:border-[#10b981]/30 transition-all hover:bg-[#0f172a]/80"
              >
                <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center text-white mb-5 shadow-lg`}>
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold text-white mb-3 group-hover:text-[#10b981] transition-colors">
                  {feature.title}
                </h3>
                <p className="text-[#64748b] leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-4 bg-[#0f172a]/50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4">How It Works</h2>
            <p className="text-[#94a3b8]">
              Get started with FutScout in minutes
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-[#10b981]/10 text-[#10b981] flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                1
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Search Players</h3>
              <p className="text-[#64748b]">
                Use our smart search to find players from any league or club worldwide
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-[#10b981]/10 text-[#10b981] flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                2
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Analyze Data</h3>
              <p className="text-[#64748b]">
                View detailed statistics, performance metrics, and player attributes
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-[#10b981]/10 text-[#10b981] flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                3
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Make Decisions</h3>
              <p className="text-[#64748b]">
                Compare players and build squads to make informed scouting decisions
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Technology Section */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="bg-gradient-to-br from-[#0f172a] to-[#0f172a]/50 rounded-2xl border border-[#1e293b] p-8 lg:p-12">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold text-white mb-4">Powered By Technology</h2>
              <p className="text-[#94a3b8] max-w-2xl mx-auto">
                Built with modern technology stack for performance and reliability
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-lg bg-[#10b981]/10 flex items-center justify-center text-[#10b981] flex-shrink-0">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white mb-1">RapidAPI Football Data</h3>
                  <p className="text-[#64748b] text-sm">
                    Real-time player data from major football leagues worldwide
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-lg bg-purple-500/10 flex items-center justify-center text-purple-400 flex-shrink-0">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white mb-1">Groq AI</h3>
                  <p className="text-[#64748b] text-sm">
                    Lightning-fast AI-powered scouting reports and insights
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-400 flex-shrink-0">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white mb-1">FastAPI Backend</h3>
                  <p className="text-[#64748b] text-sm">
                    High-performance Python backend with async processing
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-lg bg-cyan-500/10 flex items-center justify-center text-cyan-400 flex-shrink-0">
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white mb-1">React + Vite</h3>
                  <p className="text-[#64748b] text-sm">
                    Modern frontend with lightning-fast builds and hot reload
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-gradient-to-br from-[#10b981]/10 via-transparent to-transparent">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to Scout?</h2>
          <p className="text-[#94a3b8] text-lg mb-8 max-w-xl mx-auto">
            Start discovering football talent and building your dream squad today.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/search"
              className="px-8 py-4 bg-gradient-to-r from-[#10b981] to-[#059669] text-white font-semibold rounded-xl hover:from-[#059669] hover:to-[#047857] transition-all shadow-lg shadow-emerald-500/20"
            >
              Search Players
            </Link>
            <Link
              to="/compare"
              className="px-8 py-4 bg-[#1e293b] text-white font-semibold rounded-xl hover:bg-[#334155] transition-all border border-[#334155]"
            >
              Compare Players
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}

export default About
